Fix some brew warnings & errors
Warning: We decided to not change the behaviour of `brew upgrade` so
`brew upgrade --all` is equivalent to `brew upgrade` without any other
arguments (so the `--all` is a no-op and can be removed).

Warning: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.

Error: Cask 'brew-cask' is unavailable
No longer need `brew install caskroom/cask/brew-cask`
see https://github.com/Homebrew/homebrew-core/issues/131